import { type Metadata } from 'next'
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import './globals.css'
import Sidebar from '@/components/SideBar'

export const metadata: Metadata = {
  title: 'Task Manager',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className="flex h-screen">
          {/* Sidebar stays fixed on the left */}
          <SignedIn>
            <Sidebar />
          </SignedIn>

          {/* Main content area */}
          <div className="flex flex-col flex-1">
            {/* Header at the top */}
            <header className="flex justify-end items-center p-4 gap-4 h-16 border-b">
              <SignedOut> 
                <SignInButton />
                <SignUpButton>
                  <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </header>

            {/* Page content */}
            <main className="pt-4 flex-1 overflow-y-auto">{children}</main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
